# Generated by Django 2.1.3 on 2018-12-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Tittle', models.CharField(max_length=255)),
                ('Blog_Content', models.TextField()),
                ('Blog_Image', models.ImageField(upload_to='images/')),
                ('Blog_Date', models.DateField()),
            ],
        ),
    ]
