# Generated by Django 2.1.3 on 2018-12-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogModel',
        ),
        migrations.RenameField(
            model_name='blogmodel',
            old_name='Blog_Content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='blogmodel',
            old_name='Blog_Date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='blogmodel',
            old_name='Blog_Image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='blogmodel',
            old_name='Blog_Tittle',
            new_name='Tittle',
        ),
    ]
